### GENERAL SETTINGS ###

# Site settings
title: "FSU Center for Genomics and Personalized Medicine"
description: "The FSU Center for Genomics and Personalized Medicine"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://genomics.fsu.edu"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: ___ #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#c2a87d" #"#F70031"
  primary_rgb: "223,176,97" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#4a0000" #"#33004D"
  tertiary: "#000000"
  link: "#4a0000"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  #- title: dribbble
  #  url:
  #- title: facebook
  #  url:
  - title: twitter
    url: http://twitter.com/FSUgenomics
  #- title: instagram
  #  url:
  #- title: tumblr
  #  url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - The Center for Genomics and Personalized Medicine
    - The Florida State University
    - Tallahassee, FL 32306
    - United States
email: vera@genomics.fsu.edu
tel: 8502968372


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Gary Tyson
    position: Advisory Committee Chair
    text: Professor of Computer Science
    img: tyson.jpg
    social:
      - title: envelope #use for email address
        url: mailto:tyson@cs.fsu.edu
      # - title: twitter
        # url: http://twitter.com/handle
  - name: Dave Gilbert
    position: Advisory Committee Member
    text: Professor of Biological Science
    img: gilbert.jpg
    social:
      - title: envelope #use for email address
        url: mailto:gilbert@bio.fsu.edu
      # - title: twitter
        # url: http://twitter.com/handle
  - name: Jonathan Dennis
    position: Advisory Committee Member
    text: Associate Professor of Biological Science
    img: dennis.jpg
    social:
      - title: envelope #use for email address
        url: mailto:dennis@bio.fsu.edu
      # - title: twitter
        # url: http://twitter.com/handle
  - name: Michelle Arbeitman
    position: Advisory Committee Member
    text: Associate Professor of Biomedical Sciences
    img: arbeitman.jpg
    social:
      - title: envelope #use for email address
        url: mailto:michelle.arbeitman@med.fsu.edu
      # - title: twitter
        # url: http://twitter.com/handle

affiliates:
  - name: James Fadool
    text: Associate Professor of Biological Science
    img: fadool.jpg
    social:
      - title: envelope
        url: mailto:jfadool@bio.fsu.edu
  - name: Hank Bass
    text: Associate Professor of Biological Science
    img: bass.jpg
    social:
      - title: envelope
        url: mailto:bass@bio.fsu.edu
  - name: Yanming Yang
    text: Assistant In Bioinformatics, Translational Sciences Lab
    img: yanming.jpg
    social:
      - title: envelope
        url: mailto:yanming.yang@med.fsu.edu
  - name: Yanchang Wang
    text: Associate Professor of Biomedical Sciences
    img: yanchang.jpg
    social:
      - title: envelope
        url: mailto:yanchang.wang@med.fsu.edu
  - name: Michael Roper
    text: Associate Professor of Biochemistry
    img: roper.jpg
    social:
      - title: envelope
        url: mailto:roper@chem.fsu.edu
  - name: Choogon Lee
    text: Associate Professor of Biomedical Sciences
    img: choogon.jpg
    social:
      - title: envelope
        url: mailto:clee@neuro.fsu.edu
  - name: Jinfeng Zhang
    text: Associate Professor of Statistics
    img: jinfeng.jpg
    social:
      - title: envelope
        url: mailto:jinfeng@stat.fsu.edu
  - name: Jian Feng
    text: Assistant Professor of Biological Science
    img: jian.jpg
    social:
      - title: envelope
        url: mailto:feng@bio.fsu.edu
  - name: Hengli Tang
    text: Professor of Biological Science
    img: tang.jpg
    social:
      - title: envelope
        url: mailto:tang@bio.fsu.edu
  - name: Jamila Horabin
    text: Associate Professor of Biomedical Sciences
    img: jamila.jpg
    social:
      - title: envelope
        url: mailto:jamila.horabin@med.fsu.edu
  - name: Darin Rokyta
    text: Associate Professor of Biological Science
    img: rokyta.jpg
    social:
      - title: envelope
        url: mailto:drokyta@bio.fsu.edu

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "The Center for Genomics and Personalized Medicine (CGPM) at Florida State University aims to enable research programs by providing consulting, data analysis support, and training for research projects with genomic components."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
